swagger: '2.0'
info:
  title: Time Travelers' Emporium MCP
  description: MCP Streamable endpoint for Copilot Studio custom connector
  version: 1.0.0
host: time-travelers-backend-api.azurewebsites.net
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /mcp:
    post:
      summary: Time Travelers' Emporium MCP Server
      description: Streamable MCP endpoint for Agentic protocol in Copilot Studio.
      operationId: InvokeMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      parameters:
        - in: body
          name: body
          description: MCP client message payload (opaque to OpenAPI)
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Success
        '4XX':
          description: Client error
        '5XX':
          description: Server error
