swagger: '2.0'
info:
  title: Time Travelers Emporium MCP
  description: MCP Streamable endpoint for Copilot Studio custom connector
  version: 1.0.0
host: time-travelers-backend-api.azurewebsites.net
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /mcp:
    post:
      summary: Invoke MCP Server
      description: Streamable MCP endpoint for Agentic protocol in Copilot Studio
      operationId: InvokeMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      parameters:
        - name: mcpRequest
          in: body
          description: MCP request payload
          required: true
          schema:
            $ref: '#/definitions/MCPRequest'
      responses:
        '200':
          description: Successful MCP response
          schema:
            $ref: '#/definitions/MCPResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  MCPRequest:
    type: object
    required:
      - method
    properties:
      method:
        type: string
        description: MCP method name
        example: "tools/list"
      params:
        type: object
        description: Method parameters
        example: {}
  MCPResponse:
    type: object
    properties:
      result:
        type: object
        description: Success result
      error:
        $ref: '#/definitions/MCPError'
  MCPError:
    type: object
    properties:
      code:
        type: integer
        description: Error code
      message:
        type: string
        description: Error message
  ErrorResponse:
    type: object
    properties:
      error:
        type: string
        description: Error description
