swagger: '2.0'
info:
  title: Time Travelers Emporium MCP Test
  version: 1.0.0
host: time-travelers-backend-api.azurewebsites.net
schemes:
  - https
paths:
  /mcp:
    post:
      operationId: TestMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      parameters:
        - name: request
          in: body
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Success
          schema:
            type: object
