swagger: '2.0'
info:
  title: Time Travelers Emporium MCP
  version: 1.0.0
host: time-travelers-backend-api.azurewebsites.net
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /mcp:
    post:
      operationId: InvokeMCP
      summary: Invoke MCP Server
      description: MCP Streamable endpoint
      x-ms-agentic-protocol: mcp-streamable-1.0
      x-ms-visibility: internal
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: object
