name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'shared/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci

    - name: Install backend dependencies
      run: npm ci --workspace=backend

    - name: Install shared dependencies
      run: npm ci --workspace=shared

    - name: Build backend
      run: npm run build --workspace=backend

    - name: Create deployment package
      run: |
        mkdir deploy-package
        cp -r backend/dist/* deploy-package/
        cp backend/package.json deploy-package/
        cp -r shared deploy-package/
        # Create a simple package.json for production dependencies only
        cd deploy-package
        npm init -y
        npm pkg set main="server.js"
        npm pkg set scripts.start="node server.js"
        npm pkg set engines.node=">=18.0.0"
        # Install only production dependencies
        npm install express cors helmet compression dotenv

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'time-travelers-backend-api'
        package: './deploy-package'
